"""align_schema_indexes_and_defaults

Revision ID: ece11f39d71e
Revises: 
Create Date: 2026-03-22 23:51:46.024539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ece11f39d71e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_logs', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               server_default='',
               existing_nullable=False)
    op.alter_column('action_logs', 'details',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('action_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('shift_tasks', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default='0',
               existing_nullable=False)
    op.alter_column('shift_tasks', 'reviewed_count',
               existing_type=mysql.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('shift_tasks', 'violation_count',
               existing_type=mysql.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('shift_tasks', 'work_duration',
               existing_type=mysql.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('shift_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               server_default='',
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               server_default='0',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default='1',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shift_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('shift_tasks', 'work_duration',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shift_tasks', 'violation_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shift_tasks', 'reviewed_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shift_tasks', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('action_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('action_logs', 'details',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('action_logs', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
